### ISSUE TITLE
other(maven引入github release版本)

### ISSUE THREAD

**Issue by TheKingOfGhost** [tocrhz/mqtt-spring-boot-starter#1]
您好，我想请教下您是如何在github发布的版本，pom可以直接拉下来作为依赖引入，我看别人都是说要配置maven settings文件的，我自己也尝试了在github上发布版本，直接引入则拉不下来，请问这是需要操作什么？我没找到对应的资料，可以帮忙解惑下吗

**Comment by TheKingOfGhost** [comment]
明白了，自己上传到中央仓库对吧

**Comment by tocrhz** [comment]
我是参考的这位大佬的文章


最新版Jar包发布到中央仓库详细教程 - 阿提说说 - OSCHINA - 中文开源技术交流社区




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tocrhz/mqtt-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月28日(星期六) 上午10:41
收件人:&nbsp;"tocrhz/mqtt-spring-boot-starter"<mqtt-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [tocrhz/mqtt-spring-boot-starter] other(maven引入github release版本) (#1)





 
明白了，自己上传到中央仓库对吧

**Comment by TheKingOfGhost** [comment]
谢谢您
