### ISSUE TITLE
spring boot变量注入问题解决

### ISSUE THREAD

**Issue by shanjunmei** [tocrhz/mqtt-spring-boot-starter#15]
https://github.com/tocrhz/mqtt-spring-boot-starter/blob/cbcd10b382187352efda901a411268b588359675/src/main/java/com/github/tocrhz/mqtt/autoconfigure/MqttSubscribeProcessor.java#L31
，只需要将这里的逻辑放到after里面处理就可以了

**Comment by tocrhz** [comment]
你原来的程序，肯定是哪个地方处理了，初始化放在 postProcessAfterInitialization 里没用，我实际用了下 de.smartsquare:mqtt-starter 这个库 0.14.0 版本， 没有你说的效果。
你可以新建一个项目引用 de.smartsquare:mqtt-starter 这个库试一下，并不能替换参数，所以肯定是你的程序有地方处理了

**Comment by shanjunmei** [comment]
表达式的计算可以使用这个BeanExpressionResolver 处理，spring kafka 源码里面扒出来的， de.smartsquare:mqtt-starter 这个我之前用的时候，确实是解析出来了正确的topic，具体细节我也不知，现在回看确实有点奇葩，我已经自己处理过了
