### ISSUE TITLE
默认的Convert List转[]byte有坑

### ISSUE THREAD

**Issue by rc452860** [tocrhz/mqtt-spring-boot-starter#16]
Spring中Boot默认的List转[]byte在CollectionToArrayConverter中把双方都转成组成对象List会抽取成内部组成的对象，但是[]byte会变成byte.

![image](https://user-images.githubusercontent.com/3949222/188422460-1fe1fe77-7be4-4b88-8cfd-abe3287fa509.png)

建议先转换成String.
![image](https://user-images.githubusercontent.com/3949222/188422573-a4c006cb-a52e-4051-80bd-142fc1ab768b.png)

**Comment by tocrhz** [comment]
这个应该优先使用自定义的转换类，没有或者转换不了才走到SpringBoot默认的转换器里面，这样应该比较合理

**Comment by tocrhz** [comment]
发个新版本解决这个bug
