### ISSUE TITLE
影响springboot的Controller在使用@PathVariable接受参数时其值会多拼接了一对双引号

### ISSUE THREAD

**Issue by jansanw** [tocrhz/mqtt-spring-boot-starter#19]
影响springboot的Controller在使用@PathVariable接受参数时其值会多拼接了一对双引号，引入1.2.8版本时出现，1.2.7版本没有此bug

**Comment by tocrhz** [comment]
测试了下，是被序列化类 JacksonStringSerialize 影响了，已经将所有自带的序列化反序列化的类从spring管理中移除了。直接更新下版本 1.2.8.1 就好。

**Comment by tocrhz** [comment]
如果暂时更新不了，直接把类复制出来改改也可以的，我就经常这么干 ^_^

**Comment by jansanw** [comment]
感谢你的开源。&nbsp;


-zhanshan-
***@***.***



&nbsp;
