### ISSUE TITLE
不支持$开关的订阅

### ISSUE THREAD

**Issue by friendbookok** [tocrhz/mqtt-spring-boot-starter#20]
如@MqttSubscribe(value = "$SYS/brokers/{brokerId}/clients/{clientId}/subscribed", qos = 1, shared = true)
    public void sub(String topic, @NamedValue("clientId") String clientId, @Payload String payload) {...
订阅后，在emqx上看不到有这个订阅存在。但我看测试代码是有发这个订阅出去。
log如下所示：
 Mqtt client 'msgCenter_0' subscribe success. topics : ('$queue/lc/+/+/+/+/+/+', 1),('$queue/lc/+/+/+/+/+/+/delay/+', 1),('$queue/lc/+/+/+/+/+/+/msgCenter', 1),('$queue/lc/+/+/+/+', 1),('$queue/lc/temp/msgCenter/transactionDel', 1),('$queue/$SYS/brokers/+/clients/+/subscribed', 1)
04/24 15:12:08.992 [main]   INFO d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed

**Comment by tocrhz** [comment]
试了下能看到，是否是看错了呢？
另外新版本的 emqx5.0 已经不支持 $queue 开头的共享订阅了，如果要使用共享订阅，最好加上 groups，兼容性更好

**Comment by friendbookok** [comment]
我知道了，是权限问题，改成超级用户就可以了，错误日志如下所示：
emqx.log.2:2023-04-24T18:04:58.842639+08:00 [warning] clientid: msgCenter_0, ipaddr: {10,2,15,25}, line: 356, mfa: emqx_authz:authorize_non_superuser/5, msg: authorization_permission_denied, peername: 10.2.15.25:65166, source: file, topic: $SYS, username: <<"user">>

**Comment by friendbookok** [comment]
这个问题可以关闭了
