### ISSUE TITLE
应用自重启后同一条消息会处理两次

### ISSUE THREAD

**Issue by achengovo** [tocrhz/mqtt-spring-boot-starter#22]
在使用restartEndpoint.restart();自重启后同一条消息，出现重复处理，每重启一次就多一次处理
![image](https://github.com/tocrhz/mqtt-spring-boot-starter/assets/87600405/d3473457-5aa0-4279-8270-f2f91e4d87cd)

![image](https://github.com/tocrhz/mqtt-spring-boot-starter/assets/87600405/4304a4b8-fbba-4384-9f98-7901eddf0881)

![image](https://github.com/tocrhz/mqtt-spring-boot-starter/assets/87600405/24f71882-df5c-47fa-943c-c9137f66e4fb)

**Comment by tocrhz** [comment]
保留消息需要手动清理，收到后往同一个topic发送个0字节的消息就可以了， new 个 byte[0]

**Comment by tocrhz** [comment]
明白了，原来是这样重启，关闭的时候把 MqttSubscriber.SUBSCRIBERS 清理一下就行了。
不过你这种重启，只要是静态变量全都有可能出问题
