### ISSUE TITLE
topic上的retained保留消息怎么清除掉

### ISSUE THREAD

**Issue by chengpei** [tocrhz/mqtt-spring-boot-starter#6]
调用MqttPublisher传的retained为true，发送了保留消息，后面我想清除掉这个保留消息，据说是要给该topic再发一次保留消息，同时payload要传空，但是我看send方法里payload为空的话就没有发送了，那怎么清除topic上的保留消息呢？

**Comment by chengpei** [comment]
MqttConnector.getDefaultClient().publish("/topic/xxx", new byte[0], 0, true);
这样好像也行

**Comment by tocrhz** [comment]
发送方法里有判断
```java
if (bytes == null || bytes.length == 0) {
        return;
}
```
保留消息清除如果要发送空的话， `new byte[0]` 估计也不行。

**Comment by tocrhz** [comment]
判断里的 `bytes.length == 0` 去掉了

**Comment by chengpei** [comment]
> 判断里的 `bytes.length == 0` 去掉了

嗯嗯，那发送new byte[0] 就可以清除了

**Comment by tocrhz** [comment]
1.2.3
